### ISSUE TITLE
大大，预览页面看不了了

### ISSUE THREAD

**Issue by wangerzi** [zhangxinxu/mockup#1]

**Comment by zhangxinxu** [comment]
感谢反馈，已修。

**Comment by wangerzi** [comment]
还有个小问题就是，POST请求示例接口([https://raw.githubusercontent.com/zhangxinxu/mockup/master/dist/views/cgi/succ.json](https://raw.githubusercontent.com/zhangxinxu/mockup/master/dist/views/cgi/succ.json))报404，直接 GET 访问就有返回数据，看了下 Network ，请求方法是 OPTIONS，但是看了下逻辑代码，type 确实是 post，然后也没找到问题。
```
        $.ajax({
		url: G_DATA.postUrl,
		type: 'post',
		dataType: 'json',
		success: function (json) {
			elBtn.parent().after('<p>'+ json.msg +'</p>');
		},
        error: function () {
            elBtn.parent().after('<p>ajax请求失败</p>');
        }
	});
```
General 如下所示：
> Request URL: https://raw.githubusercontent.com/zhangxinxu/mockup/master/dist/views/cgi/succ.json
Request Method: OPTIONS
Status Code: 400 Bad Request
Remote Address: 151.101.228.133:443
Referrer Policy: no-referrer-when-downgrade

返回报文如下所示：
> 400: Invalid request

**Comment by zhangxinxu** [comment]
需要本地开启服务预览。Github预览不支持post~
