### ISSUE TITLE
资源文件怎么里怎么引用呢

### ISSUE THREAD

**Issue by ghost** [zhangxinxu/mockup#3]
大大，
我的images文件应该在哪创建，img src=""里边怎么填呢
  <img src="" alt="">

**Comment by zhangxinxu** [comment]
根据dist中文件目录书写，使用相对地址。
img src="../../static/images/xxx.png"

**Comment by awnawnawn** [comment]
对了，大大，昨天我在当当买的css选择器到了。这边想跟您缺认下，这本书后边是这么写的么？(第一本css世界是去年在京东买的)
![IMG_20200414_113429](https://user-images.githubusercontent.com/47672657/79183672-b3583600-7e44-11ea-86b8-02d5c1a99315.jpg)
