### ISSUE TITLE
设置为GKB

### ISSUE THREAD

**Issue by ghost** [zhangxinxu/mockup#4]
项目格式为gbk，我把html文件都设置gbk格式了，后面该如何设置呢，在run.js把 utf-8都设置了gbk，运行的时候报错了
![image](https://user-images.githubusercontent.com/47672657/79427897-fc9cb700-7ff7-11ea-85f2-c1fc0c59c079.png)

**Comment by zhangxinxu** [comment]
请问报什么错误，是页面错误吗？writeFile和readFile那里设置的编码encoding: 'utf8' 改成其他编码格式试试。

**Comment by awnawnawn** [comment]
![Snipaste_2020-04-16_10-44-57](https://user-images.githubusercontent.com/47672657/79431318-db8a9500-7ffc-11ea-9bd7-08c19840dd8b.png)
![Snipaste_2020-04-16_15-59-42](https://user-images.githubusercontent.com/47672657/79431320-dc232b80-7ffc-11ea-98ea-33f3fc741f65.png)

**Comment by ghost** [comment]
![Snipaste_2020-04-16_15-59-42](https://user-images.githubusercontent.com/47672657/79431382-f52bdc80-7ffc-11ea-9130-159fba63e6ba.png)

**Comment by ghost** [comment]
我改了writeFile和readFile为gbk也不行呢

**Comment by zhangxinxu** [comment]
搜索了下，这里有篇文章可以供你参考：http://fengmk2.github.io/blog/2014/iconv-lite/iconv-lite.html
